config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"    
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: { maximum: 10 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
      @tasks = Task.all
  end

  def show
      set_task
  end

  def new
      @task = Task.new
  end

  def create
      @task = Task.new(task_params)
      
      if @task.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
      end
  end

  def edit
      set_task
  end

  def update
      set_task

    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    set_task
    @task.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end

  private
  
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:content, :status)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>

  <div>
<%= task %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container">
      
<%= render 'layouts/flash_tasks' %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

<% if task.errors.any? %>

    <div id="error_explanation">
      <h2>
<%= pluralize(task.errors.count, "error") %>
 prohibited this message from being saved:</h2>

      <ul>
        
<% task.errors.full_messages.each do |msg| %>

          <li>
<%= msg %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

<%= f.label :status, 'ステータス' %>

<%= f.text_field :status %>

<%= f.label :content, 'タスク' %>

<%= f.text_field :content %>

<%= f.submit '投稿' %>

<% end %>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 の編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  
<% @tasks.each do |task| %>

    <li>
<%= link_to task.id, task %>
 : 
<%= task.status %>
 &gt; 
<%= task.content %>
</li>
  
<% end %>

</ul>

<%= link_to '新規の投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: 
<%= @task.id %>
 の詳細ページ</h1>

<p>ステータス: 
<%= @task.status %>
</p>
<p>タスク: 
<%= @task.content %>
</p>

<%= link_to '一覧に戻る', tasks_path %>


<%= link_to 'このメッセージを編集する', edit_task_path(@task) %>

<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>